name: aldernet_prod
channels:
  - conda-forge
  - defaults
  - r
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - absl-py
  - aiohttp
  - aiosignal
  - alsa-lib
  - asciitree
  - astunparse
  - async-timeout
  - atk-1.0
  - attr
  - attrs
  - blinker
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - cached-property
  - cached_property
  - cachetools
  - cairo
  - cartopy
  - certifi
  - cffi
  - cfgrib
  - charset-normalizer
  - click
  - contourpy
  - cryptography
  - curl
  - cycler
  - dbus
  - eccodes
  - entrypoints
  - expat
  - fasteners
  - fftw
  - findlibs
  - flatbuffers
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freeglut
  - freetype
  - fribidi
  - frozenlist
  - gast
  - gdk-pixbuf
  - geos
  - gettext
  - giflib
  - glib
  - glib-tools
  - google-auth
  - google-auth-oauthlib
  - google-pasta
  - graphite2
  - graphviz
  - grpc-cpp
  - grpcio
  - gst-plugins-base
  - gstreamer
  - gstreamer-orc
  - gtk2
  - gts
  - h5py
  - harfbuzz
  - hdf4
  - hdf5
  - icu
  - idna
  - importlib-metadata
  - jack
  - jasper
  - jpeg
  - keras
  - keras-preprocessing
  - keyutils
  - kiwisolver
  - krb5
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libabseil
  - libaec
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcap
  - libcblas
  - libclang
  - libclang13
  - libcups
  - libcurl
  - libdb
  - libdeflate
  - libedit
  - libev
  - libevent
  - libffi
  - libflac
  - libgcc-ng
  - libgcrypt
  - libgd
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libglu
  - libgomp
  - libgpg-error
  - libiconv
  - liblapack
  - libllvm15
  - libnetcdf
  - libnghttp2
  - libnsl
  - libogg
  - libopenblas
  - libopus
  - libpng
  - libpq
  - libprotobuf
  - librsvg
  - libsndfile
  - libsqlite
  - libssh2
  - libstdcxx-ng
  - libsystemd0
  - libtiff
  - libtool
  - libudev1
  - libuuid
  - libvorbis
  - libwebp
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - libzip
  - libzlib
  - lz4-c
  - markdown
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mpg123
  - msgpack-python
  - multidict
  - munkres
  - mysql-common
  - mysql-libs
  - ncurses
  - nspr
  - nss
  - numcodecs
  - oauthlib
  - openjpeg
  - openssl
  - opt_einsum
  - packaging
  - pandas
  - pango
  - pathlib
  - pcre2
  - pillow
  - pip
  - pixman
  - ply
  - proj
  - protobuf
  - pthread-stubs
  - pulseaudio
  - pyasn1
  - pyasn1-modules
  - pycparser
  - pydot
  - pyjwt
  - pyopenssl
  - pyparsing
  - pyproj
  - pyprojroot
  - pyqt
  - pyqt5-sip
  - pyshp
  - pysocks
  - python
  - python-dateutil
  - python-eccodes
  - python-flatbuffers
  - python_abi
  - pytz
  - pyu2f
  - qt-main
  - re2
  - readline
  - requests
  - requests-oauthlib
  - rsa
  - scipy
  - setuptools
  - shapely
  - sip
  - six
  - snappy
  - sqlite
  - tensorboard
  - tensorboard-data-server
  - tensorboard-plugin-wit
  - tensorflow
  - tensorflow-base
  - tensorflow-estimator
  - termcolor
  - tk
  - toml
  - tornado
  - typing-extensions
  - typing_extensions
  - tzdata
  - unicodedata2
  - urllib3
  - werkzeug
  - wheel
  - wrapt
  - xarray
  - xcb-util
  - xcb-util-image
  - xcb-util-keysyms
  - xcb-util-renderutil
  - xcb-util-wm
  - xorg-fixesproto
  - xorg-inputproto
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxfixes
  - xorg-libxi
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - yarl
  - zarr
  - zipp
  - zlib
  - zstd
  - pip:
    - alembic
    - cloudpickle
    - databricks-cli
    - distlib
    - docker
    - filelock
    - flask
    - gitdb
    - gitpython
    - greenlet
    - gunicorn
    - itsdangerous
    - jinja2
    - joblib
    - jsonschema
    - llvmlite
    - mako
    - mlflow
    - numba
    - numpy
    - platformdirs
    - pyarrow
    - pyrsistent
    - pyyaml
    - querystring-parser
    - ray
    - scikit-learn
    - shap
    - slicer
    - smmap
    - sqlalchemy
    - sqlparse
    - tabulate
    - threadpoolctl
    - tqdm
    - virtualenv
    - websocket-client
    - install -e .
