channels:
  - conda-forge
  - defaults
dependencies:
  - cfgrib
  - click
  - keras
  - matplotlib
  - mlflow
  - numpy
  - pip
  - pyprojroot
  - pytest
  - python>=3.10
  - tensorflow
  - xarray
  - pip:
    - ray
    - torch
